modLoader = "javafml"
loaderVersion = "[33,)"
license = "BSD-3-Clause License for Code"
# issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId = "barter"
version = "${file.jarVersion}"
displayName = "Barter"
# updateJSONURL="http://myurl.me/"
# displayURL="http://example.com/"
logoFile = "logo.png"
credits = "Lemon Slice Studio"
authors = "RoitoLeo, MalayP"
description = '''This is a simple mod that allows players to barter.'''
[[dependencies.barter]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.barter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side = "BOTH"
[[dependencies.barter]]
modId = "silveroakoutpost"
mandatory = true
versionRange = "[0.3.5-Alpha,)"
ordering = "NONE"
side = "BOTH"
